export const initialProducts = [
  {
    id: 1,
    name: "Ноутбук MacBook Air",
    category: "ноутбук",
    brand: "Apple",
    color: "серебристый",
    price: 90000,
    os: "macOS",
  },
  {
    id: 2,
    name: "Смартфон Samsung Galaxy",
    category: "смартфон",
    brand: "Samsung",
    color: "черный",
    price: 40000,
    os: "Android",
  },
  {
    id: 3,
    name: "Наушники Sony WH-1000XM4",
    category: "наушники",
    brand: "Sony",
    color: "синий",
    price: 20000,
  },
  {
    id: 4,
    name: "Ноутбук Lenovo ThinkPad",
    category: "ноутбук",
    brand: "Lenovo",
    color: "черный",
    price: 50000,
    os: "Windows",
  },
  {
    id: 5,
    name: "Планшет iPad",
    category: "планшет",
    brand: "Apple",
    color: "белый",
    price: 60000,
    os: "iOS",
  },
  {
    id: 6,
    name: "Смартфон Xiaomi Mi 11",
    category: "смартфон",
    brand: "Xiaomi",
    color: "белый",
    price: 30000,
    os: "Android",
  },
  {
    id: 7,
    name: "Ноутбук Samsung Galaxy Book",
    category: "ноутбук",
    brand: "Samsung",
    color: "серебристый",
    price: 70000,
    os: "Windows",
  },
  {
    id: 8,
    name: "Смартфон iPhone 12",
    category: "смартфон",
    brand: "Apple",
    color: "черный",
    price: 80000,
    os: "iOS",
  },
  {
    id: 9,
    name: "Ноутбук Dell XPS 13",
    category: "ноутбук",
    brand: "Dell",
    color: "серебристый",
    price: 85000,
    os: "Windows",
  },
  {
    id: 10,
    name: "Наушники Bose QuietComfort 35",
    category: "наушники",
    brand: "Bose",
    color: "черный",
    price: 25000,
  },
];
